name: Release - Build & Push (version tag)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: notes-app/api  # ← si vous voulez éviter de le répéter partout
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: notes-app/api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push versioned image
        uses: docker/build-push-action@v6
        with:
          context: notes-app
          file: notes-app/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:${{ github.ref_name }}